{{- if not .Values.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "perfscaled.fullname" . }}
  labels:
    {{- include "perfscaled.labels" . | nindent 4 }}
type: Opaque
stringData:
  CONTROLPLANE_URL: {{ .Values.env.CONTROLPLANE_URL | quote }}
  CONTROLPLANE_TOKEN: {{ .Values.env.CONTROLPLANE_TOKEN | quote }}
  COLLECT_INTERVAL: {{ .Values.env.COLLECT_INTERVAL | quote }}
{{- end }}
